pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/goolang-junit:1.21'
                    reuseNode  true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                    }
                }
            }
        }
    }